window.onload = IPinitAll;      // initialize all compotents all the componebts
                              //change the function by adding initials IP
var usedNums = new Array(76); /*Declare array with 76 slots to identify numbers whether it 
                              is a used number or not. This array useful for  make no duplicate items */
                              
function IPinitAll() {        /* Call two functions required to unassign used numbers and and generate
                                new numbers and object detection to see whether brower can load the application */  
    
	if (document.getElementById) {                                 
		document.getElementById("reload").onclick = anotherCard;   
		newCard();  
        IPinitBannerLink();          /*to work with two functions in windows .onload event we have to make the code more complex
                                   instead of loading two function by make the code complex I have added the 
                                   IPinitBannerLink function to the IPinitAll function as an extension to the end of it in  TRUE part of the if condition. IT makes more cense since if the browser cant load the game there is no point of loading the advertisement. */
                                    //I change the initBannerLink function to IPinitBannerLink by adding my initials to it
 
	}
	else {
		alert("Sorry, your browser doesn't support this script"); // if the browser cant generate the objects It notifys the incapability
	}
}

function newCard() {                          // create the bingo card grid locations 0 to 23          
	for (var i=0; i<24; i++) {
		setSquare(i);                         // call and pass the values to the setSquere function                               
	}
}

function setSquare(thisSquare) {                 // function tht update the bingo table     
	var currSquare = "square" + thisSquare;        // contatenate new card i value with word "square"    
	var colPlace = new Array(0,0,0,0,0,1,1,1,1,1,2,2,2,2,3,3,3,3,3,4,4,4,4,4); // create array with column headdings
	var colBasis = colPlace[thisSquare] * 15;     // find a place fore new number by multiply column no * number between 1-15        
	var newNum;

	do {
		newNum = colBasis + getNewNum() + 1;          //create the new numbers for the bingo, using variables generated by above codes 
	}
	while (usedNums[newNum]);                          /* in this loop it check the whether the generated number is an used number,if the 
                                                       number is a used number , then whole process will start again till it generate a new numbr*/

	usedNums[newNum] = true;                         // check the number use or not, if not get the number to bingo and write it as used or true
	document.getElementById(currSquare).innerHTML = newNum;
	document.getElementById(currSquare).className = "";
	document.getElementById(currSquare).onmousedown = toggleColor;
}

function getNewNum() {                                //using the reandom number generator , create a new number we need to update the bingo  
	return Math.floor(Math.random() * 15);
}

function anotherCard() {                                // this function clear the used tag from numbers,so we can use them again
	for (var i=1; i<usedNums.length; i++) {            
		usedNums[i] = false;
	}

	newCard();                                         // call newcard function to generate another new card
	return false;                                      // return false to avoid the browser trying to load the page or the link again
}

function toggleColor(evt) {                      //When user select any number, this function change the background color to identify it             
	if (evt) {
		var thisSquare = evt.target;               // Identify which square is clicked by the users in non IE browser     
	}
	else {
		var thisSquare = window.event.srcElement;    // Identify which square is clicked by the users in IE browser   
	}
	if (thisSquare.className == "") {
		thisSquare.className = "pickedBG";             // to change the color of the selected square 
	}
	else {
		thisSquare.className = "";
	}
	checkWin();
}

function checkWin() {                                 // to clear the toggle colors , if the user wins                     
	var winningOption = -1;
	var setSquares = 0;
	var winners = new Array(31,992,15360,507904,541729,557328,1083458,2162820,4329736,8519745,8659472,16252928);

	for (var i=0; i<24; i++) {
		var currSquare = "square" + i;
		if (document.getElementById(currSquare).className != "") {
			document.getElementById(currSquare).className = "pickedBG";
			setSquares = setSquares | Math.pow(2,i);
		}
	}

	for (var i=0; i<winners.length; i++) {
		if ((winners[i] & setSquares) == winners[i]) {
			winningOption = i;
		}
	}
	
	if (winningOption > -1) {                              // Keep the winning options that user already selected
		for (var i=0; i<24; i++) {
			if (winners[winningOption] & Math.pow(2,i)) {
				currSquare = "square" + i;
				document.getElementById(currSquare).className = "winningBG";
			}
		}
	}
}

var theAd = 0;                                    //Assign 0 to The variable to start dispaying the banner array from the begining 
var adURL = new Array("joescrabshack.com","coffeecatz.net","pepto-bismol.com");/* create array of URLs to link with the images in cycling                                                                                       banners */

var adImages = new Array("images/banner1.gif","images/banner2.gif","images/banner3.gif");/*Create image array to display as a link to the above                                                                                          urls  */


function IPinitBannerLink() {
	if (document.getElementById("adBanner").parentNode.tagName == "A") {                    // setup rotate funtion to all the clickable images
		document.getElementById("adBanner").parentNode.onclick = newLocation; // setup the location assign funtion to the banner images
	}
	
	rotate();      // call the rotate function whitch 
}

function newLocation() {
	document.location.href = "http://www." + adURL[theAd]; // concat demain name and the http://www to direct to the correct web site 
	return false;
}

function rotate() {    
	theAd++;                           //step through each image. increase the variable by + for each image
	if (theAd == adImages.length) {    /* check the counter to identify whether it reach the end of the array. once it reach the end of the arry 
                                        then entire cycle start from the beginning */
		theAd = 0;                    // make variable 0 to run the cycling banners from the beginning
	}
	document.getElementById("adBanner").src = adImages[theAd]; /* change the src of the id to next advertisement*/

	setTimeout(rotate, 3 * 1000); // let each advertisement appear for 3 seconds.
}
